import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from utils.logger import get_logger
from config import Config
import os

logger = get_logger(__name__)

class EmailHandler:
    """Handles sending email summaries to users"""
    
    def __init__(self):
        self.smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('SMTP_PORT', '587'))
        self.sender_email = os.getenv('SENDER_EMAIL')
        self.sender_password = os.getenv('SENDER_PASSWORD')
        self.enabled = bool(self.sender_email and self.sender_password)
        
        if not self.enabled:
            logger.warning("Email functionality disabled - missing SMTP credentials")
    
    def send_summary_email(self, recipient_email: str, summary_data: dict) -> bool:
        """
        Send a summary via email
        
        Args:
            recipient_email: Email address to send to
            summary_data: Dict containing summary information
            
        Returns:
            bool: True if sent successfully, False otherwise
        """
        if not self.enabled:
            logger.error("Cannot send email - SMTP not configured")
            return False
        
        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"TeaL;DR Summary - {summary_data.get('server_name', 'Your Server')}"
            msg['From'] = self.sender_email
            msg['To'] = recipient_email
            
            # Create plain text version
            text_content = self._create_text_summary(summary_data)
            
            # Create HTML version
            html_content = self._create_html_summary(summary_data)
            
            part1 = MIMEText(text_content, 'plain')
            part2 = MIMEText(html_content, 'html')
            
            msg.attach(part1)
            msg.attach(part2)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            
            logger.info(f"Sent email summary to {recipient_email}")
            return True
            
        except Exception as e:
            logger.error(f"Error sending email: {e}")
            return False
    
    def _create_text_summary(self, data: dict) -> str:
        """Create plain text version of summary"""
        text = f"""
TeaL;DR Summary
===============

Server: {data.get('server_name', 'N/A')}
Period: {data.get('time_period', 'N/A')}

{data.get('content', '')}

"""
        if data.get('topics'):
            text += "\nKey Topics:\n"
            for topic in data['topics']:
                text += f"  • {topic}\n"
        
        text += "\n---\nThis summary was generated by TeaL;DR Discord Bot\n"
        return text
    
    def _create_html_summary(self, data: dict) -> str:
        """Create HTML version of summary"""
        topics_html = ""
        if data.get('topics'):
            topics_html = "<h3>Key Topics</h3><ul>"
            for topic in data['topics']:
                topics_html += f"<li>{topic}</li>"
            topics_html += "</ul>"
        
        html = f"""
        <html>
          <head>
            <style>
              body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
              .header {{ background-color: #5865F2; color: white; padding: 20px; }}
              .content {{ padding: 20px; }}
              .footer {{ background-color: #f4f4f4; padding: 10px; text-align: center; font-size: 12px; }}
              .info {{ background-color: #f9f9f9; padding: 10px; margin: 10px 0; border-left: 4px solid #5865F2; }}
            </style>
          </head>
          <body>
            <div class="header">
              <h1>📬 TeaL;DR Summary</h1>
            </div>
            <div class="content">
              <div class="info">
                <strong>Server:</strong> {data.get('server_name', 'N/A')}<br>
                <strong>Period:</strong> {data.get('time_period', 'N/A')}
              </div>
              <p>{data.get('content', '').replace(chr(10), '<br>')}</p>
              {topics_html}
            </div>
            <div class="footer">
              <p>This summary was generated by TeaL;DR Discord Bot</p>
              <p>Manage your preferences in Discord with /dm-settings</p>
            </div>
          </body>
        </html>
        """
        return html

email_handler = EmailHandler()
